### ISSUE TITLE
URL for linkified links is wrong

### ISSUE THREAD

**Issue by analpi** [risacher/ep_linkify2#1]
Steps:
* Made a test link by typing [[TestLink]]
* Click on linkified text
* Taken to 127.0.0.1:9001/static/TestLink, when it should be 127.0.0.1:9001/p/TestLink

**Comment by alx** [comment]
Hi @xander-page ,

I've made a fork fixing this issue. You'll have to deploy it manually:

```
cd /opt/etherpad/etherpad-lite/ # your etherpad-lite folder
cd node_modules
rm -rf ep_linkify2
git clone https://github.com/alx/ep_linkify2.git
```

Hope it helps,

Alex

**Comment by risacher** [comment]
Thank you both.  It was still working for me because I hadn't pulled recent etherpadlite.

**Comment by risacher** [comment]
Didn't use your PR because it's not reverse-proxy friendly and the timeslider was, in fact, broken.  But I very much appreciate you pointing to where it was broken.
